### ISSUE TITLE
"github.com/oskca/gopherjs-electron/api/main/menu" not found

### ISSUE THREAD

**Issue by ghost** [oskca/gopherjs-electron#1]
Got the Hello world running inside electron. 

am trying to get the menu example going.
I did the go generate in the root already but not sure where the "github.com/oskca/gopherjs-electron/api/main/menu" is...

````
gopherjs build
cannot find package "github.com/oskca/gopherjs-electron/api/main/menu" in any of:
	/usr/local/opt/go/libexec/src/github.com/oskca/gopherjs-electron/api/main/menu (from $GOROOT)
	/Users/apple/workspace/go/src/github.com/oskca/gopherjs-electron/api/main/menu (from $GOPATH)

```

**Comment by pjebs** [comment]
The author changed the project file structure. All API is now in 1 place which you can see from GoDocs:

https://godoc.org/github.com/oskca/gopherjs-electron

**Comment by ghost** [comment]
Ok thanks.
Since then I started using astielectron.
So will close...
